---
title: "Engineering a linear scan"
output: html_document
---

```{r setup, echo=FALSE, messages=FALSE}
knitr::opts_chunk$set(echo=F)

library(tidyverse)
library(ggiraph)
library(DBI)
library(ggiraph)

conn <- dbConnect(RSQLite::SQLite(), "../demo-db.sqlite")
```

```{r}
results <- tbl(conn, "results") %>%
  collect() %>%
  mutate(
    method = str_extract(parameters, "simple|avx(51)?2"),
    storage = str_extract(parameters, "i16_aligned|float_aligned"),
    use_filter = str_detect(parameters, "filter=true"),
    recall_wish = as.double(str_extract(parameters, "0\\.\\d+")),
    qps = 100 / (running_time_ns / 1000000000)
  )
```

## Recall

The diagonal line represents the minimum recall required to each configuration.

```{r fig.width=10}
p_recall = results %>%
  filter(use_filter) %>%
  ggplot(aes(x=recall_wish, y=recall, color=storage,
             tooltip=str_c("recall=", recall))) +
  geom_abline(intercept=0,slope=1) +
  geom_point_interactive() +
  facet_wrap(vars(method)) +
  theme_bw()

girafe(code = print(p_recall))
```

## Queries per second

```{r fig.widht=10}
p_qps <- results %>%
  filter(use_filter) %>%
  mutate(conf = fct_reorder(interaction(method, storage), qps)) %>%
  ggplot(aes(x=conf, y=qps, color=storage, shape=method,
             tooltip=str_c("qps=", qps))) +
  geom_point_interactive() +
  facet_wrap(vars(recall_wish)) +
  coord_flip() +
  ylim(0, NA) +
  labs(x="Configuration",
       y="Queries per second") +
  theme_bw() +
  theme(legend.position='top')

girafe(code = print(p_qps))
```

